version: '3'

services:
  syaroho-rating:
    build: ./
    env_file:
      - local.env
    command: run
    volumes:
      - ./data:/app/data
      - ./src:/app
  test:
    build: ./
    env_file:
      - local.env
    entrypoint: ""
    volumes:
      - ./data:/app/data
      - ./syaroho_rating:/app/syaroho_rating
