name: Docker Image CI

on:
  push:
    branches:
      - develop
    pull_request:
      branches:
        - 16-feature-ステージング環境を作る

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest-stg -t $ECR_REGISTRY/$ECR_REPOSITORY:$(git rev-parse --short HEAD) .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest-stg
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$(git rev-parse --short HEAD)
    
